---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook
spec:
  serviceAccountName: pipeline
  triggers:
    - name: petclinic-webhook
      interceptors:
        - cel:
            overlays:
            - key: short_sha
              expression: "body.after.truncate(7)"
            - key: branch_name
              expression: "body.ref.split('/')[2]"
      bindings:
        - ref: gogs-triggerbinding
      template:
        ref: petclinic-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-webhook
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: webhook
spec:
  port:
    targetPort: http-listener
  to:
    kind: "Service"
    name: el-webhook
    weight: 100
