apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-push-gitops
spec:
  params:
    - name: repo-url
      type: string
    - name: source-subdirectory
      type: string
      default: 'source'
    - name: app-context
      type: string
    - name: dockerfile
      type: string
    - name: revision
      type: string
    - default: 'image-registry.openshift-image-registry.svc.cluster.local:5000'
      name: image-registry
      type: string
    - default: <YOUR_PROJECT>      
      name: image-repository
      type: string
    - name: config-repo-url
      type: string
    - name: config-revision
      type: string
    - name: config-subdirectory
      type: string
      default: 'config'
  tasks:
    - name: git-clone-source
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: subdirectory
          value: $(params.source-subdirectory)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: generate-artifact
      params:
        - name: MAVEN_IMAGE
          value: registry.access.redhat.com/ubi8/openjdk-11:1.3
        - name: GOALS
          value:
            - package
            - '-f'
            - $(params.source-subdirectory)/$(params.app-context)/pom.xml
        - name: PROXY_PROTOCOL
          value: http
      runAfter:
        - git-clone-source
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
    - name: build-and-push-image
      params:
        - name: IMAGE
          value: >-
            $(params.image-registry)/$(params.image-repository)/$(params.app-context):$(params.revision)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.source-subdirectory)/$(params.app-context)
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: oci
      runAfter:
        - generate-artifact
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
    - name: git-clone-config
      params:
        - name: url
          value: $(params.config-repo-url)
        - name: revision
          value: $(params.config-revision)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: subdirectory
          value: $(params.config-subdirectory)
      runAfter:
        - build-and-push-image
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
      # use source workspace to avoid antiaffinity issues with volumes
          # workspace: config
          workspace: source
    - name: kustomize-and-push
      params:
        - name: image
          value:  $(params.image-registry)/$(params.image-repository)/$(params.app-context):$(params.revision)
        - name: manifest-dir
          value: $(params.source-subdirectory)/$(params.app-context)/k8s
        - name: git-revision
          value: $(params.config-revision)
        - name: config-subdirectory
          value: $(params.config-subdirectory)
      runAfter:
        - git-clone-config
      taskRef:
        kind: Task
        name: kustomize-and-push
      workspaces:
      # use same workspace to avoid antiaffinity issues with volumes
        - name: config
          workspace: source
        - name: source
          workspace: source
  workspaces:
    - name: source
    - name: maven-settings
    # - name: config